name: Build with Maven

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # This is what an attacker might try to add
      - name: Attempt to print a secret
        run: |
          echo "NVD key is: $TEST_SECRET"

      - name: Build
        run: mvn -q -DskipTests=false test
